separate `public-check`

diff --git a/.github/workflows/project-ci.yml b/.github/workflows/project-ci.yml
--- a/.github/workflows/project-ci.yml
+++ b/.github/workflows/project-ci.yml
@@ -12,6 +12,27 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  public-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Setup Copybara
+        uses: ./.github/actions/setup-copybara
+      - name: Set up Git credentials
+        run: |
+          git config --global credential.helper store
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+      - name: Dry run Copybara
+        run: java -jar copybara.jar migrate project/copy.bara.sky push ${{ github.ref }} --squash --dry-run
+      - name: Check for a public commit message
+        env:
+          PR_BODY: ${{ github.event.pull_request.body }}
+        run: |
+          if ! echo "$PR_BODY" | grep -Pzos '<public>[\s\S]*?</public>' > /dev/null; then
+            echo "::error::PR body must contain a <public>commit message</public>"
+            exit 1
+          fi
+
   check:
     runs-on: ubuntu-latest
     defaults:
@@ -27,20 +48,3 @@ jobs:
       - run: npm ci --no-audit --no-fund
       - run: npm run tsc
       - run: npm test
-      - name: Check for a public commit message
-        env:
-          PR_BODY: ${{ github.event.pull_request.body }}
-        run: |
-          if ! echo "$PR_BODY" | grep -Pzos '<public>[\s\S]*?</public>' > /dev/null; then
-            echo "::error::PR body must contain a <public>commit message</public>"
-            exit 1
-          fi
-      - name: Setup Copybara
-        uses: ./.github/actions/setup-copybara
-      - name: Set up Git credentials
-        run: |
-          git config --global credential.helper store
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-      - name: Dry run Copybara
-        run: java -jar copybara.jar migrate project/copy.bara.sky push ${{ github.ref }} --squash --dry-run
