switch CI to `pull_request`

diff --git a/.github/workflows/project-ci.yml b/.github/workflows/project-ci.yml
--- a/.github/workflows/project-ci.yml
+++ b/.github/workflows/project-ci.yml
@@ -1,7 +1,7 @@
 name: CI
 
 on:
-  push:
+  pull_request:
     paths:
       - "project/**"
       - "!project/copy.bara.sky"
@@ -26,26 +26,9 @@ jobs:
       - run: npm ci --no-audit --no-fund
       - run: npm run tsc
       - run: npm test
-      - uses: actions/github-script@v7
-        with:
-          script: |
-            const prs = await github.rest.pulls.list({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`,
-              state: 'open'
-            });
-
-            console.log(prs);
-
-            const pr = prs[0];
-            if (!pr) {
-              console.log('No open PR found for this branch.');
-              return;
-            }
-
-            console.log(pr);
-
-            if (!/<public>.*<\/public>/.test(pr.body || '')) {
-              core.setFailed('PR body must contain a `<public>commit message</public>`');
-            }
+      - name: Check for a public commit message
+        run: |
+          if ! grep -q '<public>.*</public>' <<< "${{ github.event.pull_request.body }}"; then
+            echo "::error::PR body must contain a <public>commit message</public>"
+            exit 1
+          fi
